CREATE TABLE "FLIGHT" (
	"ID" integer IDENTITY PRIMARY KEY,
 	"FROMLOC" varchar(20),
 	"TOLOC" varchar(20),
 	"DEPARTURE" timestamp,
 	"ARRIVAL" timestamp,
 	"AIRPLANE_ID" integer
);

CREATE TABLE "PASSENGER" (
 	"ID" integer IDENTITY PRIMARY KEY,
 	"NAME" varchar(20),
 	"GENDER" varchar(20)
);

CREATE TABLE "PASSENGER_CONTACT_INFO" (
 	"PASSENGER_ID" integer NOT NULL,
 	"EMAIL" varchar(20),
 	"PHONE" varchar(20)
);

CREATE TABLE "AIRPLANE" (
	"ID" integer IDENTITY PRIMARY KEY,
	"MODEL_NUMBER" varchar(20),
 	"CAPACITY" integer
);

CREATE TABLE "BOOKING" (
 	"ID" integer IDENTITY PRIMARY KEY,
 	"FLIGHT_ID" integer,
 	"PASSENGER_ID" integer
);


ALTER TABLE "FLIGHT" ADD CONSTRAINT "FLIES" FOREIGN KEY ("AIRPLANE_ID")
 	REFERENCES "AIRPLANE"("ID")
 	MATCH SIMPLE
 	ON DELETE NO ACTION
 	ON UPDATE NO ACTION;

ALTER TABLE "PASSENGER_CONTACT_INFO" ADD CONSTRAINT "HAS_CONTACT_INFO" FOREIGN KEY ("PASSENGER_ID")
	REFERENCES "PASSENGER"("ID")
 	MATCH SIMPLE
 	ON DELETE NO ACTION
 	ON UPDATE NO ACTION;

ALTER TABLE "BOOKING" ADD CONSTRAINT "HAS_BOOKING" FOREIGN KEY ("FLIGHT_ID")
 	REFERENCES "FLIGHT"("ID")
 	MATCH SIMPLE
 	ON DELETE NO ACTION
 	ON UPDATE NO ACTION;

ALTER TABLE "BOOKING" ADD CONSTRAINT "BOOKS" FOREIGN KEY ("PASSENGER_ID")
	REFERENCES "PASSENGER"("ID")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;